### PR TITLE
fix: Improve abort handling

### LINKED ISSUE #316: Sending response although request has been cancelled
## Description

Even if an XHR has been cancelled PollyJS will still try to send a response. 
This will lead to an error. 

### Shareable Source

```js
    const unsubscribe = new Subject();
    this.httpClient.get('/rest/my-api').pipe(takeUntil(unsubscribe)).subscribe((result) => console.log(result));
    unsubscribe.next();
    unsubscribe.complete();
```

PollsJS will still call
```js
xhr.respond(response.statusCode, response.headers, response.body);
```
on the already cancelled request resulting in an error.

I think the issue can be fixed in the XHRAdapter:
```js
if (!xhr.aborted) {
xhr.respond(response.statusCode, response.headers, response.body);
}
```

### Error Message & Stack Trace

```
pollyjs-core.js:7258 mock
pollyjs-core.js:7284 Errored ➞ GET /rest/my-api
pollyjs-core.js:7285 Error: INVALID_STATE_ERR - 0
    at verifyRequestOpened (pollyjs-adapter-xhr.js:6788)
    at FakeXMLHttpRequest.setStatus (pollyjs-adapter-xhr.js:7028)
    at FakeXMLHttpRequest.respond (pollyjs-adapter-xhr.js:7193)
    at XHRAdapter.respondToRequest (pollyjs-adapter-xhr.js:11077)
    at XHRAdapter._callee14$ (pollyjs-adapter-xhr.js:10865)
    at tryCatch (pollyjs-adapter-xhr.js:68)
    at Generator.invoke [as _invoke] (pollyjs-adapter-xhr.js:294)
    at Generator.prototype.<computed> [as next] (pollyjs-adapter-xhr.js:120)
    at asyncGeneratorStep (pollyjs-adapter-xhr.js:1961)
    at _next (pollyjs-adapter-xhr.js:1983)
```

### Config

```js
      Polly.register(XHRAdapter);

      const polly = new Polly('mock', {
        adapters: ['xhr']
      });

      const { server } = polly;

      server.get('rest/my-api').intercept((req, res) => { res.send({}); });
```

### Dependencies

```json
{
    "@pollyjs/adapter-xhr": "~4.0.2",
    "@pollyjs/core": "~4.0.2",
}
```

## Relevant Links

https://github.com/nbfr/pollyjs-dream-app
Branch: test/cancelled-request

Run "npm run start-mock" and open the app on "http://localhost:4200" to see the error in the browser console.

## Environment

Node.JS v10.16.3
win32 10.0.1832
npm 6.9.0

### PR DESCRIPTION
**Pull request by offirgolan**
## Description

Improve overall abort handling across the adapters.

## Motivation and Context

Resolves #316.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] My code follows the code style of this project.
- [x] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [x] I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: packages/@pollyjs/adapter-xhr/src/index.js [hunk 1]
```diff
@@ -61,10 +61,22 @@ export default class XHRAdapter extends Adapter {
     this.xhr.restore();
   }
 
+  onRequest(pollyRequest) {
+    const { xhr } = pollyRequest.requestArguments;
+
+    if (xhr.aborted) {
+      pollyRequest.abort();
+    } else {
+      xhr.addEventListener('abort', () => pollyRequest.abort());
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-xhr/src/index.js]: General comment that applies to these abort event listeners, we should clean these event listeners up when the request is complete or aborted.

**Comment by offirgolan** [comment]
Still need to add tests for the node-http-adapter but a couple of things have come up so I'll try to finish up this PR by the end of the week.
