### PR TITLE
fix(ember): Config read from project root

### LINKED ISSUE #297: @pollyjs/ember stores recordings in [projectRoot]node_modules/@pollyjs/ember/recordings
`@pollyjs/ember@4.0.0` is storing the recordings in `[projectRoot]/node_modules/@pollyjs/ember/recordings`.
Also, configuration options in config/polly.js are ignored.

It seems to me, that this.root in https://github.com/Netflix/pollyjs/blob/6423839d9aeb9b0318ae69251d8bafcd28933408/packages/%40pollyjs/ember/index.js#L78 and https://github.com/Netflix/pollyjs/blob/6423839d9aeb9b0318ae69251d8bafcd28933408/packages/%40pollyjs/ember/index.js#L86-L89 is pointing to the root of the addon, not to the root of the project using @pollyjs/ember. When I change `this.root` to `this.project.root` everything is working as expected.

I'm using ember-cli@3.15.1.

### PR DESCRIPTION
**Pull request by jasonmit**
`this.root` points to the addon's location within `node_modules` - not the project root.

Since we cannot bank on `this.project` to always be available to find the project root folder (see: #276) we have to use the current working directory of the process to determine the root directory of the project - which Ember also seems to use internally.

Fixes #297

### CODE REVIEW

File: packages/@pollyjs/ember/index.js [hunk 1]
```diff
@@ -75,7 +77,7 @@ module.exports = {
       server: {}
     };
 
-    let configPath = path.join(this.root, 'config', 'polly.js');
+    let configPath = path.join(root, 'config', 'polly.js');
```
Comment (offirgolan) [inline packages/@pollyjs/ember/index.js]: What are your thoughts on doing something like

`const projectRoot = this.project && this.project.root ? this.project.root : root`?

Comment (jasonmit) [reply packages/@pollyjs/ember/index.js]: I like it, will update

Comment (jasonmit) [reply packages/@pollyjs/ember/index.js]: Updated
