### PR TITLE
fix(ember): BREAKING load polly config for ember by its own module

### LINKED ISSUE #276: pollyjs config is undefined when reusing ember build and running ember test
Hello pollyjs contributors and devs,
I am not sure if this is a bug report or a question :)

## TL;DR
pollyjs config from consuming ember app is not available inside the polly js addon methods, when reusing the build, which happens when running the command,
 `ember test --path <build folder name>`

## Description
I am using pollyjs/@ember package for my ember project, and it works just fine, when I run the tests using the command, `ember test`. 

But when I try to reuse an existing build of my ember project(`ember test --path <build folder name. by default, 'dist'>`), I run into this error in command line:

```
Cannot read property 'enabled' of undefined

Stack Trace and Error Report: /var/folders/l3/zfkk52zd2qsdh8lbhdz6gy1r000lf7/T/error.dump.466e5463069e16ef55ccda6970db9a12.log
```

On further looking into the logs and debugging the ember node process, the error was happening in the `testemMiddleware()` method in the [`@pollyjs/ember/index.js`](https://github.com/Netflix/pollyjs/blob/ee25c77f1f469f20754b458b582319947f727c7b/packages/%40pollyjs/ember/index.js#L44) file as show below:

```js
testemMiddleware(app) {
    if (this._config.enabled) { // <== `this._config` is undefined here
      registerExpressAPI(app, this._config.server);
    }
  },
```

And the root cause seems to be that pollyjs `this.app.options.pollyjs` config defined and retrieved from the consuming ember app into the addon, is available only in the `included()` hook; but not available inside the other methods.

### Error Message & Stack Trace

```
stack: TypeError: Cannot read property 'enabled' of undefined
    at Class.testemMiddleware (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/@pollyjs/ember/index.js:45:22)
    at middlewares.forEach.middleware (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/server/index.js:183:9)
    at Array.forEach (<anonymous>)
    at Server.injectMiddleware (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/server/index.js:182:19)
    at Server.createExpress (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/server/index.js:133:10)
    at Server.start (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/server/index.js:41:10)
    at App.startServer (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/app.js:231:24)
    at App.getServer (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/app.js:235:17)
    at Bluebird.using (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/testem/lib/app.js:74:38)
    at tryCatcher (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/shsridha/workspace/srd-backstop/gryphon-fe/node_modules/bluebird/js/release/promise.js:699:18)
```

### Config

Defined inside the `ember-cli-build.js`
```js
pollyjs: {
      enabled: EmberApp.env() !== 'production',
      server: {
        expiresIn: null,
        keepUnusedRequests: false
      }
    },
```

## Environment

```
Node.js v10.15.0
darwin 18.7.0
6.4.1
1.15.2
```

### PR DESCRIPTION
**Pull request by jasonmit**
Currently we rely on `included()` to be called and read all config options from `app.options` derived from `ember-cli-build.js` at the time the app is built.  This strategy is no longer reliable since you can run tests against previously built assets which means `included` is never called nor is `app.options` available since the app isn't being built.

Instead, I introduced `config/polly.js` and rely upon my own function to determine what the env is (see: https://github.com/ember-cli/ember-cli/issues/8922 as to why I had to go with that approach).

This is a breaking change for @pollyjs/ember so we'll need to release a new major for the addon.

Resolves #276

### CODE REVIEW

File: packages/@pollyjs/ember/index.js [hunk 1]
```diff
@@ -2,18 +2,49 @@
 
 'use strict';
 
+const fs = require('fs');
 const path = require('path');
 const { registerExpressAPI, Defaults } = require('@pollyjs/node-server');
+const parseArgs = require('minimist');
 
-const { assign } = Object;
+function determineEnv() {
```
Comment (jasonmit) [inline packages/@pollyjs/ember/index.js]: Lifted from a previous method I wrote for ember-cli-dotenv:
https://github.com/fivetanley/ember-cli-dotenv/blob/master/index.js#L49-L68

File: docs/node-server/overview.md [hunk 2]
```diff
@@ -32,7 +32,7 @@ const { Server } = require('@pollyjs/node-server');
 const server = new Server({
   quiet: true,
   port: 4000,
-  apiNamespace: '/pollyjs'
+  apiNamespace: '/polly'
```
Comment (jasonmit) [inline docs/node-server/overview.md]: Just making the docs references consistent since they all sort of vary.
