### PR TITLE
Deprecates adapter & persister `name` in favor of `id`

### LINKED ISSUE #309: issue with `name` property when creating a custom adapter in TS
## Description

When creating a custom adapter using typescript, the name property conflicts with the `Function.name` constructor. not sure how to get around this, would it be possible to rename the property to `adapterName` or something similar? 

### Shareable Source

```js
class NewAdapter extends Adapter {
  // ...
  static get name() {
    return 'new-adapter';
  }
// ...
}
```

### Error Message & Stack Trace

```
Static property 'name' conflicts with built-in property 'Function.name' of constructor function 'NewAdapter'.
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/adapter": "^4.0.2"
}
```

## Relevant Links

https://github.com/microsoft/TypeScript/issues/442

## Environment

Node.js v12.6.0
darwin 18.7.0
yarn 1.19.1
npm 6.9.0

### PR DESCRIPTION
**Pull request by jasonmit**
Done in a backwards compatible way.  In the next major we can remove the deprecations.

Fixes #309

### CODE REVIEW

File: packages/@pollyjs/core/tests/unit/-private/container-test.js [hunk 1]
```diff
@@ -27,16 +27,20 @@ describe('Unit | Container', function() {
...
     it('.register() - validation', function() {
-      class NoName extends Factory {
+      class NoId extends Factory {
         /* eslint-disable-next-line getter-return */
-        static get name() {}
+        static get id() {}
       }
 
       class NoType extends Factory {
+        static get id() {
```
Comment (jasonmit) [inline packages/@pollyjs/core/tests/unit/-private/container-test.js]: masked exception since constructor.name was always a thing

File: tests/integration/adapter-tests.js [hunk 2]
```diff
@@ -228,7 +228,8 @@ export default function adapterTests() {
     expect(resolved).to.have.members([1, 2, 3]);
   });
 
-  it('should work with CORS requests', async function() {
+  // NOTE: test very unstable because of typicode.com being down
+  it.skip('should work with CORS requests', async function() {
```
Comment (jasonmit) [inline tests/integration/adapter-tests.js]: This test has been failing off and on for a couple months now, disabling.

File: packages/@pollyjs/persister-rest/src/index.js [hunk 3]
```diff
@@ -4,10 +4,16 @@ import { buildUrl } from '@pollyjs/utils';
 import ajax from './ajax';
 
 export default class RestPersister extends Persister {
-  static get name() {
+  static get id() {
     return 'rest';
   }
 
+  static get name() {
```
Comment (jasonmit) [inline packages/@pollyjs/persister-rest/src/index.js]: All of these name getter proxies need to sit on the persister/adapter classes instead of base classes because:

```js
class Foo {
        static get name() {
            return 'foo';
        }
    }

    class Bar extends Foo {}

    Bar.name; // "Bar" not "foo"
```

File: tests/helpers/setup-fetch-record.js [hunk 4]
```diff
@@ -29,9 +29,11 @@ setupFetchRecord.beforeEach = function(options = {}) {
 
 setupFetchRecord.afterEach = function() {
   afterEach(async function() {
-    this.polly.pause();
-    await this.fetchRecord({ method: 'DELETE' });
-    this.polly.play();
+    if (this.polly) {
```
Comment (jasonmit) [inline tests/helpers/setup-fetch-record.js]: Possible for test suite to fail before `this.polly` is set and made the stderr annoying to scroll through since we always assume it was.

File: packages/@pollyjs/core/src/polly.js [hunk 5]
```diff
@@ -3,7 +3,7 @@ import { MODES, assert } from '@pollyjs/utils';
 import { version } from '../package.json';
 
 import Logger from './-private/logger';
-import Container from './-private/container';
+import Container, { nameOfFactory } from './-private/container';
```
Comment (offirgolan) [inline packages/@pollyjs/core/src/polly.js]: iirc rollup has had issues supporting default and named exports. Might need to switch them both to a named export.

File: packages/@pollyjs/core/src/-private/container.js [hunk 6]
```diff
@@ -1,7 +1,19 @@
 import { assert } from '@pollyjs/utils';
 
+export function nameOfFactory(Factory) {
```
Comment (offirgolan) [inline packages/@pollyjs/core/src/-private/container.js]: Should this be `idOfFactory` or `factoryId`?

File: packages/@pollyjs/adapter-fetch/src/index.js [hunk 7]
```diff
@@ -8,10 +8,16 @@ const IS_STUBBED = Symbol();
...
 export default class FetchAdapter extends Adapter {
-  static get name() {
+  static get id() {
     return 'fetch';
   }
 
+  static get name() {
+    // NOTE: deprecated in 4.1.0 but proxying since it's possible "core" is behind
+    // and therefore still referencing `name`.  Remove in 5.0.0
+    return this.id;
```
Comment (offirgolan) [inline packages/@pollyjs/adapter-fetch/src/index.js]: Should we just release a new major version instead of having to deal with all of these deprecations?

File: tests/helpers/setup-fetch-record.js (hunk 4 above)
Comment (offirgolan) [reply tests/helpers/setup-fetch-record.js]: Might be good to add an inline comment about this.

File: packages/@pollyjs/core/src/polly.js [hunk 8]
```diff
@@ -262,7 +262,7 @@ export default class Polly {
 
     if (typeof nameOrFactory === 'function') {
       container.register(nameOrFactory);
-      adapterName = nameOrFactory.name;
+      adapterName = nameOfFactory(nameOrFactory);
```
Comment (offirgolan) [inline packages/@pollyjs/core/src/polly.js]: `adapterId`

File: packages/@pollyjs/adapter-fetch/src/index.js (hunk 7 above)
Comment (jasonmit) [reply packages/@pollyjs/adapter-fetch/src/index.js]: It's a minor change imo and will help anyone with custom adapters to migrate without reading docs.

File: packages/@pollyjs/core/src/polly.js (hunk 5 above)
Comment (jasonmit) [reply packages/@pollyjs/core/src/polly.js]: and our tests still pass with this issue?

File: tests/helpers/setup-fetch-record.js (hunk 4 above)
Comment (jasonmit) [reply tests/helpers/setup-fetch-record.js]: Done

File: packages/@pollyjs/core/src/-private/container.js (hunk 6 above)
Comment (jasonmit) [reply packages/@pollyjs/core/src/-private/container.js]: Done

File: packages/@pollyjs/core/src/polly.js (hunk 8 above)
Comment (jasonmit) [reply packages/@pollyjs/core/src/polly.js]: Done
