### PR TITLE
fix(adapter-fetch): Correctly handle Request instance passed into fetch

### LINKED ISSUE #255: Bug: Fetch Adapter support for Request objects is incomplete
As of https://github.com/Netflix/pollyjs/pull/220, the Fetch Adapter allows you pass in a Request object as the only argument. However, it will simply extract the URL from the Request, and not use any of the other parameters.

This means if I have code being tested that uses Request objects to POST with a bunch of headers, like this:
```
const reqOpts = {
    body: xml,
    method: "POST",
    headers: {
      Accept: "application/xml",
      "Content-Type": "application/xml",
      "X-custom-header": "secret value"
    }
  };
req = new Request(url, reqOpts);
fetch(req);
```

Polly will do a GET to `url`, with a minimal set of headers.

I suspect this could be mostly fixed by modifying this code:
https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/adapter-fetch/src/index.js#L41

To be:
```
      // Support Request object
      if (typeof url === 'object' && 'url' in url) {
        options = url;
        url = url.url; 
      }
```

I'm testing this solution for us, I'll let you know how it goes.

### PR DESCRIPTION
**Pull request by offirgolan**
## Description

Correctly handle passing a Request instance to fetch. 

```js
fetch(new Request('/api/foo', { method: 'POST' }), { body: 'bar' });
```

## Motivation and Context

Resolves #255.

The approach taken to solve for this is by patching the global Request class and storing the passed in `url` and `options`. This allows us to not only have direct access to the passed in body (e.g. no need to re-read it off the Request instance) but also not needing to hardcode which properties to take off the instance. 

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] My code follows the code style of this project.
- [x] My commits and the title of this PR follow the [Conventional Commits Specification](https://www.conventionalcommits.org).
- [x] I have read the [contributing guidelines](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js [hunk 1]
```diff
@@ -75,8 +75,8 @@ describe('Integration | Fetch Adapter | Init', function() {
         adapterOptions
       });
 
-      expect(polly.adapters.get('fetch').native).to.equal(fetch);
-      expect(polly.adapters.get('fetch').native).to.not.equal(
+      expect(polly.adapters.get('fetch').nativeFetch).to.equal(fetch);
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js]: Should add tests around this new Request stub

File: packages/@pollyjs/adapter-fetch/src/index.js [hunk 2]
```diff
@@ -26,23 +28,72 @@ export default class FetchAdapter extends Adapter {
...
+
+    defineProperty(context.Request, IS_STUBBED, { value: true });
 
     context.fetch = (url, options = {}) => {
+      let respond;
+
       // Support Request object
-      if (typeof url === 'object' && 'url' in url) {
-        url = url.url;
+      if (typeof url === 'object' && url[IS_REQUEST]) {
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-fetch/src/index.js]: Could use `instanceof Request` here instead and would eliminate the additional `IS_REQUEST` prop

Comment (offirgolan) [reply packages/@pollyjs/adapter-fetch/src/index.js]: That would break if an actual native request gets passed in since we extend the native Request class.

```js
class R extends window.Request {}

new R('/') instanceof window.Request // true
new R('/') instanceof R // true
```

Comment (jasonmit) [reply packages/@pollyjs/adapter-fetch/src/index.js]: Can compare `instanceOfR.constructor === R`

Comment (jasonmit) [reply packages/@pollyjs/adapter-fetch/src/index.js]: Actually I'm not sure I understand your comment.

Are you saying you worry that an instance of `Request,` that isn't an instance of our `ExtendedRequest` class and instead the native `Request`, would get through an `instanceof ExtendedRequest` check?  That shouldn't be the case if so.

Comment (offirgolan) [reply packages/@pollyjs/adapter-fetch/src/index.js]: Ah, yeah you're totally right. My mistake above is not always comparing to the ExtendedRequest 🤦‍♂. I'll make the change to use `instanceof` 😄

File: packages/@pollyjs/adapter-fetch/src/index.js [hunk 3]
```diff
@@ -68,14 +118,20 @@ export default class FetchAdapter extends Adapter {
...
+    this.nativeFetch = null;
+    this.NativeRequest = null;
   }
 
   async passthroughRequest(pollyRequest) {
+    const { context } = this.options;
     const { options } = pollyRequest.requestArguments;
 
-    const response = await this.native.apply(global, [
+    const response = await this.nativeFetch.apply(context, [
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-fetch/src/index.js]: Nice catch

File: packages/@pollyjs/adapter-fetch/src/index.js [hunk 4]
```diff
@@ -26,23 +27,72 @@ export default class FetchAdapter extends Adapter {
...
+    this.nativeFetch = context.fetch;
+    this.NativeRequest = context.Request;
+
+    /*
+      Patch the Request class so we can store all the passed in options. This
+      allows us the access the `body` directly instead of having to do
+      `await req.blob()` as well as not having to hard code each option we want
+      to extract from the Request instance.
+    */
+    class ExtendedRequest extends context.Request {
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-fetch/src/index.js]: nit: `ExtendedRequest` can be hoisted up and out of `onConnect()`
