### PR TITLE
fix: Improve support for relative URLs

### LINKED ISSUE #76: Host is stripped from protocol-relative urls
**How to reproduce:**
1. Have app on `http://my-app.dev`
1. Make request to protocol-relative url `//api.dev/posts/1`

**Expected behavior**
Polly proxies this request to `api.dev` and writes response.

**Actual behavior**
Polly strips host from `//api.dev/posts/1` making it into `/posts/1` and then trying to send request to `http://my-app.dev/posts/1` instead of original url.

I found two places in code where url is modified. Here is one which caused desribed behavior:
https://github.com/Netflix/pollyjs/blob/73026d446cf207ab814db5fb653bdfee40cfe682/packages/%40pollyjs/core/src/-private/request.js#L53-L60

Seems like [is-absolute-url](https://www.npmjs.com/package/is-absolute-url) check here can be swapped with custom implementation supporting protocol-relative urls

### PR DESCRIPTION
**Pull request by offirgolan**
- Create a shared parseUrl utility that will make sure to match the provided URL string to a url-parse instance
- Support for protocol-relative URLs (Resolves #76)

### CODE REVIEW

File: packages/@pollyjs/core/tests/unit/utils/parse-url-test.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+    expect(parseUrl).to.be.a('function');
+  });
+
+  it('should exactly match passed urls', function() {
+    [
+      '/movies/1',
+      '//netflix.com/movies/1',
+      'http://netflix.com/movies/1',
+      'http://netflix.com/movies/1?sort=title&dir=asc'
+    ].forEach(url => expect(parseUrl(url).href).to.equal(url));
```
Comment (jasonmit) [inline packages/@pollyjs/core/tests/unit/utils/parse-url-test.js]: Can you add a test for the `true` argument to `parseUrl`.  Wasn't really sure how it was being used.
