### PR TITLE
fix: Puppeteer 1.7.0 support

### LINKED ISSUE #93: ci: pipeline fails against latest puppeteer (1.7.0)
Whatever breaking change happened took place between 1.6.2 and 1.7.0.  No issues on 1.6.2.

### PR DESCRIPTION
**Pull request by jasonmit**
Resolves #93 also refactored to avoid mutating the puppeteer object passed in to Polly.

### CODE REVIEW

File: packages/@pollyjs/adapter-puppeteer/src/index.js [hunk 1]
```diff
@@ -15,7 +15,9 @@ export default class PuppeteerAdapter extends Adapter {
   get defaultOptions() {
     return {
       page: null,
-      requestResourceTypes: ['xhr', 'fetch']
+
+      /* NOTE: `"other" is needed as of puppeteer 1.7.0 to capture the passthrough request */
+      requestResourceTypes: ['xhr', 'fetch', 'other']
```
Comment (jasonmit) [inline packages/@pollyjs/adapter-puppeteer/src/index.js]: Will probably do some digging to figure out why this is
